-- Publish the 100 verified shelter/OZ profiles imported on 2026-09-13.
-- Safety: only exact verified draft rows from the known import batch are affected.
WITH target(slug) AS (
  VALUES
  ('pomoc-oz-tulava-labka'),
  ('pomoc-utulok-tulacik-o-z'),
  ('pomoc-oz-zvieratkovo-sk'),
  ('pomoc-regionalne-centrum-slobody-zvierat-lucenec'),
  ('pomoc-stastne-labky-o-z'),
  ('pomoc-mesto-revuca'),
  ('pomoc-hnustanske-labky-o-z'),
  ('pomoc-oz-blaznivy-zverinec'),
  ('pomoc-oz-pes-v-nudzi'),
  ('pomoc-utulok-pre-psov-u-starej-dorky'),
  ('pomoc-oz-bullterrier-rescue-slovakia'),
  ('pomoc-oz-pes-a-macka-v-ohrozeni'),
  ('pomoc-oz-ziarsky-chlpac-mestsky-utulok-ziar-nad-hronom'),
  ('pomoc-oz-lillyen-cesta-k-novemu-zivotu'),
  ('pomoc-sloboda-zvierat'),
  ('pomoc-mesto-malacky'),
  ('pomoc-mesto-pezinok'),
  ('pomoc-oz-berry-dog'),
  ('pomoc-oz-pomoc-psikom-nova-dedinka'),
  ('pomoc-mala-farma-kosice'),
  ('pomoc-mesto-moldava-nad-bodvou'),
  ('pomoc-obec-kysak'),
  ('pomoc-oz-vychodoslovenske-labky'),
  ('pomoc-td-s-r-o'),
  ('pomoc-unia-vzajomnej-pomoci-ludi-a-psov-u-v-p'),
  ('pomoc-oz-na-konci-sveta'),
  ('pomoc-oz-utulok-pre-psikov-michalovce'),
  ('pomoc-mesto-spisska-nova-ves-mestska-policia'),
  ('pomoc-oz-utulok-stastny-psik'),
  ('pomoc-oz-zemplinska-labka'),
  ('pomoc-z-ulice-do-srdca'),
  ('pomoc-4-stvorlistky-o-z'),
  ('pomoc-mesto-mestsky-urad-kolarovo'),
  ('pomoc-mesto-nesvady'),
  ('pomoc-obec-dulovce-obecny-urad-dulovce'),
  ('pomoc-vesela-lebka-o-z'),
  ('pomoc-stastny-domov-happy-house'),
  ('pomoc-ciernousko-o-z'),
  ('pomoc-obec-dolny-ohaj'),
  ('pomoc-obec-dvory-nad-zitavou'),
  ('pomoc-oz-priatel-pes'),
  ('pomoc-oz-zatulane-labky-surany'),
  ('pomoc-oz-zatulane-psiky-sala'),
  ('pomoc-mesto-topolcany-mestsky-urad'),
  ('pomoc-utulok-zlate-moravce-o-z'),
  ('pomoc-druha-sanca-bardejov-o-z'),
  ('pomoc-sos-psiky-sos-doggies'),
  ('pomoc-obcianske-zdruzenie-srdce-pre-vsetkych'),
  ('pomoc-pomahaj-a-chran-o-z-humenske-labky'),
  ('pomoc-obec-lendak'),
  ('pomoc-utulok-kezmarok-o-z'),
  ('pomoc-mesto-levoca'),
  ('pomoc-mesto-spisske-podhradie'),
  ('pomoc-cesta-za-domovom-o-z'),
  ('pomoc-mesto-poprad'),
  ('pomoc-technicke-sluzby-mesta-presov'),
  ('pomoc-oz-chlpacik-snina'),
  ('pomoc-kynologicky-klub-karantenna-stanica-stara-lubovna'),
  ('pomoc-zvieraci-azyl-stara-lubovna'),
  ('pomoc-wolfiho-pomocna-labka'),
  ('pomoc-pomoc-nechcenym-zvieratkam-svidnik-a-okolie'),
  ('pomoc-majte-psa-spolocnost-vzajomnej-pomoci-ludi-a-psov'),
  ('pomoc-vranovsky-utulok-pre-psov'),
  ('pomoc-jana-janikova-obchodne-cinnosti'),
  ('pomoc-oz-banovski-chlpaci'),
  ('pomoc-farma-v-udoli-o-z'),
  ('pomoc-mestska-policia-mesto-brezova-pod-bradlom'),
  ('pomoc-mestska-policia-mesto-myjava'),
  ('pomoc-obec-priepasne'),
  ('pomoc-utulok-nadej-o-z'),
  ('pomoc-mesto-partizanske'),
  ('pomoc-obec-krasno'),
  ('pomoc-hafkaci'),
  ('pomoc-mesto-handlova'),
  ('pomoc-mesto-prievidza'),
  ('pomoc-oz-patrola-chlpaci-puchov'),
  ('pomoc-oz-trencianske-labky'),
  ('pomoc-trenciansky-utulok-o-z'),
  ('pomoc-dog-azyl-o-z'),
  ('pomoc-oz-tulak-sered'),
  ('pomoc-oz-docasny-domov-pre-havinkov-piestany'),
  ('pomoc-regionalne-centrum-slobody-zvierat-piestany'),
  ('pomoc-cerberus-n-o'),
  ('pomoc-oz-labky-zo-zahoria'),
  ('pomoc-zachranny-korab-o-z'),
  ('pomoc-mesto-skalica'),
  ('pomoc-regionalne-centrum-slobody-zvierat-skalica'),
  ('pomoc-sona-milianova'),
  ('pomoc-zdruzenie-na-ochranu-zvierat-trnava'),
  ('pomoc-mesto-bytca'),
  ('pomoc-oz-u-psej-matere-kysuce-ranc-korna'),
  ('pomoc-domaci-milacik-terapeut'),
  ('pomoc-mesto-dolny-kubin'),
  ('pomoc-ocami-psa-utulok-liptovsky-mikulas'),
  ('pomoc-zatulany-chlpacik-psia-nadej-o-z'),
  ('pomoc-iniciativa-ochrany-zvierat'),
  ('pomoc-mesto-martin-mestsky-urad-martin'),
  ('pomoc-oz-oravsky-nufacik'),
  ('pomoc-centrum-najdenych-zvierat-o-z'),
  ('pomoc-zilinsky-utulok-o-z')
)
UPDATE help_cases
SET
  status = 'published',
  published_at = COALESCE(published_at, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
  updated_by = 'batch-publish:2026-09-13'
WHERE
  category = 'utulky'
  AND status = 'draft'
  AND verified = 1
  AND created_at = '2026-09-13T14:11:47Z'
  AND slug IN (SELECT slug FROM target);
