import AxeBuilder from "@axe-core/playwright";
import { expect,test,type Page } from "@playwright/test";
const slug="biely-svajciarsky-ovciak",breed=`/plemena/${slug}`;
async function overflow(page:Page){const d=await page.evaluate(()=>({v:document.documentElement.clientWidth,s:document.documentElement.scrollWidth}));expect(d.s).toBeLessThanOrEqual(d.v+1)}
async function axe(page:Page,label:string){const r=await new AxeBuilder({page}).analyze();const v=r.violations.filter(x=>x.impact==="critical"||x.impact==="serious");expect(v,`${label}: ${JSON.stringify(v,null,2)}`).toEqual([])}
test("breed canonical breeder landing",async({request,page})=>{const href=`/adresar/chovatelske-stanice/plemeno/${slug}`,r=await request.get(breed);expect(r.status()).toBe(200);const h=await r.text();expect(h).toContain(`href="${href}"`);expect(h).not.toContain("/adresar/treneri?breed=");await page.goto(breed);await expect(page.locator(`a[href="${href}"]`)).toBeVisible();await page.setViewportSize({width:390,height:844});await overflow(page);await axe(page,"breed")});
test("directory profile canonical location links",async({request,page})=>{const p="/adresar/treneri/e2e-services-detail-long",r=await request.get(p);expect(r.status()).toBe(200);const h=await r.text();for(const x of ["/adresar/treneri/mesto/nitra","/adresar/treneri/okres/nitra","/adresar/treneri/kraj/nitriansky"])expect(h).toContain(`href="${x}"`);await page.goto(p);const d=page.locator("[data-internal-discovery]");await expect(d).toBeVisible();await expect(d.locator('a[href*="?"]')).toHaveCount(0);await overflow(page)});
test("breeder landing parent graph",async({request,page})=>{const p=`/adresar/chovatelske-stanice/plemeno/${slug}/kraj/nitriansky`,r=await request.get(p);expect(r.status()).toBe(200);const h=await r.text();for(const x of [`/adresar/chovatelske-stanice/plemeno/${slug}`,"/adresar/chovatelske-stanice/kraj/nitriansky",breed])expect(h).toContain(`href="${x}"`);await page.goto(p);await expect(page.locator("[data-internal-discovery] a")).toHaveCount(3);await overflow(page)});
test("general location city district region graph",async({page})=>{await page.goto("/adresar/treneri/mesto/nitra");const d=page.locator("[data-internal-discovery]");await expect(d.locator('a[href="/adresar/treneri/okres/nitra"]')).toBeVisible();await expect(d.locator('a[href="/adresar/treneri/kraj/nitriansky"]')).toBeVisible();await expect(d.locator('a[href*="?"]')).toHaveCount(0);await page.setViewportSize({width:390,height:844});await overflow(page);await axe(page,"location")});
test("article canonical breed relation is mobile-safe and accessible",async({request,page})=>{const p="/clanky/e2e-discovery-article",r=await request.get(p);expect(r.status()).toBe(200);const h=await r.text();expect(h).toContain('data-explicit-content-relation="article-breed"');expect(h).toContain(`href="${breed}"`);await page.goto(p);await expect(page.locator("h1")).toBeVisible();await page.setViewportSize({width:390,height:844});await overflow(page);await axe(page,"article")});
test("adoption canonical organization and breed",async({request,page})=>{const p="/pomoc-psom/adopcia/e2e-adoption-rex-active",r=await request.get(p);expect(r.status()).toBe(200);const h=await r.text();expect(h).toContain(`href="${breed}"`);expect(h).toContain('href="/organizacie/e2e-organizacia"');await page.goto(p);await page.setViewportSize({width:390,height:844});await overflow(page);await axe(page,"adoption")});

test("legacy directory category redirects to canonical trainer category",async({request})=>{
  const r=await request.get("/adresar/psie-skoly",{maxRedirects:0});
  expect([301,308]).toContain(r.status());
  expect(new URL(r.headers().location!).pathname).toBe("/adresar/treneri");
});
