import assert from "node:assert/strict";import fs from "node:fs/promises";import test from "node:test";import {pathToFileURL} from "node:url";
const root=new URL("../",import.meta.url),read=p=>fs.readFile(new URL("../"+p,import.meta.url),"utf8"),importTs=p=>import(pathToFileURL(new URL(p,root).pathname).href);
const migration=await read("drizzle/0060_partner_memberships_admin.sql"),platform=await read("lib/partner-platform.ts"),adminStore=await read("lib/partner-admin-store.ts"),attentionStore=await read("lib/admin-attention-queue-store.ts"),partnerAttention=await read("lib/partner-attention.ts"),adminApi=await read("lib/partner-admin-api.ts");
test("resource anchors have typed FK integrity, uniqueness and delete restriction",()=>{for(const table of ["directory_profiles","help_organizations","managed_events"])assert.match(migration,new RegExp("REFERENCES `"+table+"`\\(`id`\\) ON DELETE RESTRICT"));assert.match(migration,/CHECK \(\s*\(`entity_type`='DIRECTORY_PROFILE'/);assert.match(migration,/partner_resources_directory_unique/);assert.match(migration,/partner_resources_organization_unique/);assert.match(migration,/partner_resources_event_unique/);assert.doesNotMatch(migration,/entity_id/)});
test("membership lifecycle is role checked, historical and only one active pair",()=>{assert.match(migration,/`role` text NOT NULL CHECK \(`role` IN \('OWNER','MANAGER','EDITOR'\)\)/);assert.match(migration,/partner_memberships_active_unique.*WHERE `revoked_at` IS NULL/);assert.match(adminStore,/UPDATE partner_memberships SET revoked_at/);assert.doesNotMatch(adminStore,/DELETE FROM partner_memberships/)});
function membershipDb(row){return{prepare(){return{bind(){return{first:async()=>row}}}}}}
test("live DB membership and active account are authorization source of truth",async()=>{const {requirePartnerPermission,PartnerAuthorizationError}=await importTs("lib/partner-platform.ts");for(const role of ["OWNER","MANAGER","EDITOR"]){const found=await requirePartnerPermission("a","r","RESOURCE_VIEW",membershipDb({membershipId:"m",accountId:"a",resourceId:"r",role,accountStatus:"ACTIVE",revokedAt:null}));assert.equal(found.role,role)}await assert.rejects(()=>requirePartnerPermission("a","foreign","RESOURCE_VIEW",membershipDb(null)),PartnerAuthorizationError);await assert.rejects(()=>requirePartnerPermission("a","r","RESOURCE_VIEW",membershipDb({membershipId:"m",accountId:"a",resourceId:"r",role:"OWNER",accountStatus:"SUSPENDED",revokedAt:null})),PartnerAuthorizationError);assert.match(platform,/m\.revoked_at IS NULL/);assert.doesNotMatch(platform,/session\.permissions/)});
test("role matrix blocks editor and manager membership administration",async()=>{const {requirePartnerPermission,PartnerAuthorizationError}=await importTs("lib/partner-platform.ts");for(const role of ["EDITOR","MANAGER"]){await assert.rejects(()=>requirePartnerPermission("a","r","MEMBERSHIP_MANAGE",membershipDb({membershipId:"m",accountId:"a",resourceId:"r",role,accountStatus:"ACTIVE",revokedAt:null})),PartnerAuthorizationError)}assert.equal((await requirePartnerPermission("a","r","MEMBERSHIP_MANAGE",membershipDb({membershipId:"m",accountId:"a",resourceId:"r",role:"OWNER",accountStatus:"ACTIVE",revokedAt:null}))).role,"OWNER")});
test("audit is append-only, redacted and covers lifecycle events",()=>{assert.match(migration,/partner_audit_events_no_update/);assert.match(migration,/partner_audit_events_no_delete/);for(const action of ["ACCOUNT_CREATED","EMAIL_VERIFIED","ACCOUNT_SUSPENDED","ACCOUNT_REACTIVATED","ACCOUNT_DEACTIVATED","SESSIONS_REVOKED","MEMBERSHIP_CREATED","MEMBERSHIP_ROLE_CHANGED","MEMBERSHIP_REVOKED"])assert.match(migration,new RegExp(action));assert.match(platform,/email\|cipher\|hash\|token\|secret\|password/i);assert.doesNotMatch(platform,/UPDATE partner_audit_events|DELETE FROM partner_audit_events/)});
test("admin mutations require internal admin auth and same-origin checks",()=>{assert.match(adminApi,/getAdminApiUser/);assert.match(adminApi,/same-origin/);assert.match(adminApi,/origin/);assert.match(adminStore,/status='SUSPENDED'/);assert.match(adminStore,/status='ACTIVE'/);assert.match(adminStore,/UPDATE resource_management_sessions SET revoked_at/)});
test("Partner Attention is adapter-only with stable keys, deep links and no fake items",async()=>{const {partnerAttentionKey,partnerAttentionHref,loadPartnerAttentionItems,loadPartnerPendingSummary}=await importTs("lib/partner-attention.ts");assert.equal(partnerAttentionKey("PARTNER_CLAIM_REVIEW",12),"partner-claim:12");assert.equal(partnerAttentionHref("PARTNER_PROFILE_CHANGE_REVIEW","abc"),"/admin/partners/changes/abc");assert.deepEqual(await loadPartnerAttentionItems(),[]);assert.equal((await loadPartnerPendingSummary()).total,0);assert.doesNotMatch(migration,/partner_attention_items/);assert.match(partnerAttention,/PARTNER_COMMERCIAL_LEAD/)});
test("bounded display list and exact unbounded count remain separate",()=>{assert.equal((attentionStore.match(/LIMIT \?/g)??[]).length,9);const exact=attentionStore.slice(attentionStore.indexOf("loadExactAdminAttentionSummary"));assert.doesNotMatch(exact,/LIMIT/);for(const table of ["moderation_submissions","news_tips","directory_profile_change_requests","directory_inquiries","article_feedback","adoption_dogs","automation_findings","partner_commercial_interests","geo_points"])assert.match(exact,new RegExp(table))});
test("scope contains no claims, submissions, commercial or canonical Partner writes",async()=>{const files=(await Promise.all(["lib/partner-platform.ts","lib/partner-admin-store.ts","app/partner/profily/page.tsx","app/partner/podujatia/page.tsx"].map(read))).join("\n");assert.doesNotMatch(migration,/partner_claims|partner_commercial|premium_entitlement|billing|payments/i);assert.doesNotMatch(files,/UPDATE directory_profiles|UPDATE help_organizations|UPDATE managed_events/)});
