"use client";

import Link from "next/link";
import { ChangeEvent, useMemo, useState } from "react";
import { uploadAdminImage, adminImageUploadMessage } from "@/lib/admin-image-upload";
import { chipStateLabel, dogReportHref, dogReportStatusLabel, dogReportTypeLabel, dogSexLabel, dogSizeLabel, type AdminDogReport, type BreedOption, type ChipState, type DogReportType, type DogSex, type DogSize, type PublicLocationPrecision } from "@/lib/lost-found-dogs";
import type { LostFoundStatus } from "@/lib/lost-found-lifecycle.js";
import styles from "./admin-lost-found.module.css";

type EditorState = {
  type: DogReportType; status: LostFoundStatus; slug: string; dogName: string; sex: DogSex; breedId: string; breed: string; breedUnknown: boolean; color: string; approximateAge: string; size: DogSize;
  description: string; distinguishingMarks: string; collarDescription: string; chipped: ChipState; mainImage: string; mainImageKey: string; eventDate: string; lastSeenDateTime: string;
  region: string; district: string; city: string; locationDescription: string; publicLatitude: string; publicLongitude: string; publicLocationPrecision: PublicLocationPrecision;
  contactName: string; contactPhone: string; contactEmail: string; publicContactNote: string; source: string; sourceUrl: string; expiresAt: string; duplicateOfId: string; duplicateReason: string; internalNote: string;
};
const initial = (r?: AdminDogReport): EditorState => ({
  type:r?.type||"LOST",status:r?.status||"DRAFT",slug:r?.slug||"",dogName:r?.dogName||"",sex:r?.sex||"UNKNOWN",breedId:r?.breedId?String(r.breedId):"",breed:r?.breed||"",breedUnknown:r?.breedUnknown||false,color:r?.color||"",approximateAge:r?.approximateAge||"",size:r?.size||"UNKNOWN",
  description:r?.description||"",distinguishingMarks:r?.distinguishingMarks||"",collarDescription:r?.collarDescription||"",chipped:r?.chipped||"UNKNOWN",mainImage:r?.mainImage||"",mainImageKey:r?.mainImageKey||"",eventDate:r?.eventDate||"",lastSeenDateTime:r?.lastSeenDateTime?toLocalInput(r.lastSeenDateTime):"",
  region:r?.region||"",district:r?.district||"",city:r?.city||"",locationDescription:r?.locationDescription||"",publicLatitude:r?.publicLatitude===null||r?.publicLatitude===undefined?"":String(r.publicLatitude),publicLongitude:r?.publicLongitude===null||r?.publicLongitude===undefined?"":String(r.publicLongitude),publicLocationPrecision:r?.publicLocationPrecision||"MUNICIPALITY",
  contactName:r?.contactName||"",contactPhone:r?.contactPhone||"",contactEmail:r?.contactEmail||"",publicContactNote:r?.publicContactNote||"",source:r?.source||"EDITORIAL",sourceUrl:r?.sourceUrl||"",expiresAt:r?.expiresAt?toLocalInput(r.expiresAt):"",duplicateOfId:r?.duplicateOfId?String(r.duplicateOfId):"",duplicateReason:r?.duplicateReason||"",internalNote:r?.internalNote||"",
});
function toLocalInput(value:string){const d=new Date(value);if(Number.isNaN(d.getTime()))return "";const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,16)}
function slugify(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,100)}
export function AdminLostFoundEditor({ report, breeds }: { report?: AdminDogReport; breeds: BreedOption[] }) {
  const [state,setState]=useState(()=>initial(report)); const [saving,setSaving]=useState(false); const [uploading,setUploading]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const set=<K extends keyof EditorState>(key:K,value:EditorState[K])=>setState((s)=>({...s,[key]:value}));
  const publicHref=useMemo(()=>state.slug?dogReportHref({type:state.type,slug:state.slug}):"",[state.slug,state.type]);
  function changeName(value:string){setState((s)=>({...s,dogName:value,slug:s.slug||slugify(`${s.type==="LOST"?"strateny":"najdeny"}-${value}`)}))}
  async function uploadImage(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setUploading(true);setError("");try{const data=await uploadAdminImage(file,"lost-found");set("mainImage",data.imageUrl);set("mainImageKey",data.imageKey);setMessage(adminImageUploadMessage(data,"Ulož hlásenie."))}catch(err){setError(err instanceof Error?err.message:"Obrázok sa nepodarilo nahrať.")}finally{setUploading(false);e.target.value=""}}
  async function save(status:LostFoundStatus=state.status){setSaving(true);setError("");setMessage("");try{const payload={...state,status,breedId:state.breedId||null,mainImage:state.mainImage||null,mainImageKey:state.mainImageKey||null,lastSeenDateTime:state.lastSeenDateTime||null,publicLatitude:state.publicLatitude||null,publicLongitude:state.publicLongitude||null,contactName:state.contactName||null,contactPhone:state.contactPhone||null,contactEmail:state.contactEmail||null,sourceUrl:state.sourceUrl||null,expiresAt:state.expiresAt||null,duplicateOfId:state.duplicateOfId||null};const res=await fetch(report?`/api/admin/lost-found/${report.id}`:"/api/admin/lost-found",{method:report?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await res.json() as {report?:AdminDogReport;error?:string};if(!res.ok||!data.report)throw new Error(data.error||"Uloženie zlyhalo.");setState(initial(data.report));setMessage(status==="ACTIVE"?"Hlásenie je aktívne a verejné.":"Hlásenie bolo uložené.");if(!report)window.location.assign(`/admin/stratene-najdene/${data.report.id}?vytvorene=1`)}catch(err){setError(err instanceof Error?err.message:"Uloženie zlyhalo.")}finally{setSaving(false)}}
  return <form onSubmit={(e)=>{e.preventDefault();void save(state.status)}}>
    {(message||error)&&<div className={`${styles.message} ${error?styles.error:""}`} role="status">{error||message}</div>}
    <div className={styles.formGrid}><div className={styles.sections}>
      <section className={styles.card}><h2>1. Typ a stav prípadu</h2><div className={styles.fieldGrid}><div className={styles.field}><label>Typ</label><select value={state.type} onChange={(e)=>set("type",e.target.value as DogReportType)}><option value="LOST">LOST — stratený</option><option value="FOUND">FOUND — nájdený</option></select></div><div className={styles.field}><label>Stav</label><select value={state.status} onChange={(e)=>set("status",e.target.value as LostFoundStatus)}>{Object.entries(dogReportStatusLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div></div><div className={styles.field}><label>Slug</label><input value={state.slug} onChange={(e)=>set("slug",slugify(e.target.value))} placeholder="strateny-rex-nitra" required/></div></section>
      <section className={styles.card}><h2>2. Pes</h2><div className={styles.fieldGrid}><div className={styles.field}><label>Meno, ak je známe</label><input value={state.dogName} onChange={(e)=>changeName(e.target.value)}/></div><div className={styles.field}><label>Pohlavie</label><select value={state.sex} onChange={(e)=>set("sex",e.target.value as DogSex)}>{Object.entries(dogSexLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className={styles.field}><label>Veľkosť</label><select value={state.size} onChange={(e)=>set("size",e.target.value as DogSize)}>{Object.entries(dogSizeLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className={styles.field}><label>Čip</label><select value={state.chipped} onChange={(e)=>set("chipped",e.target.value as ChipState)}>{Object.entries(chipStateLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className={styles.field}><label>Farba</label><input value={state.color} onChange={(e)=>set("color",e.target.value)}/></div><div className={styles.field}><label>Približný vek</label><input value={state.approximateAge} onChange={(e)=>set("approximateAge",e.target.value)} placeholder="napr. 3–5 rokov"/></div></div><label className={styles.check}><input type="checkbox" checked={state.breedUnknown} onChange={(e)=>set("breedUnknown",e.target.checked)}/> Plemeno nie je známe</label>{!state.breedUnknown&&<><div className={styles.field}><label>Prepojenie na publikované plemeno</label><select value={state.breedId} onChange={(e)=>set("breedId",e.target.value)}><option value="">Bez prepojenia</option>{breeds.map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div><div className={styles.field}><label>Plemeno – text, ak nie je v atlase</label><input value={state.breed} onChange={(e)=>set("breed",e.target.value)}/></div></>}</section>
      <section className={styles.card}><h2>3. Popis a identifikácia</h2><div className={styles.field}><label>Hlavný popis</label><textarea rows={7} value={state.description} onChange={(e)=>set("description",e.target.value)} required={state.status!=="DRAFT"}/></div><div className={styles.field}><label>Rozpoznávacie znaky</label><textarea rows={4} value={state.distinguishingMarks} onChange={(e)=>set("distinguishingMarks",e.target.value)}/></div><div className={styles.field}><label>Obojok / postroj</label><textarea rows={3} value={state.collarDescription} onChange={(e)=>set("collarDescription",e.target.value)}/></div><div className={styles.field}><label>Hlavná fotografia</label><div className={styles.upload}><input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={uploadImage} disabled={uploading}/>{state.mainImage&&<button type="button" className={styles.secondary} onClick={()=>{set("mainImage","");set("mainImageKey","")}}>Odstrániť</button>}</div><small className={styles.help}>Obrázky idú do samostatného R2 priečinka lost-found. Galéria je pripravená v modeli; editor zatiaľ spravuje hlavnú fotografiu.</small></div></section>
      <section className={styles.card}><h2>4. Dátum a bezpečná lokalita</h2><div className={styles.fieldGrid}><div className={styles.field}><label>Dátum udalosti</label><input type="date" value={state.eventDate} onChange={(e)=>set("eventDate",e.target.value)} required={state.status!=="DRAFT"}/></div>{state.type==="LOST"&&<div className={styles.field}><label>Naposledy videný</label><input type="datetime-local" value={state.lastSeenDateTime} onChange={(e)=>set("lastSeenDateTime",e.target.value)}/></div>}<div className={styles.field}><label>Kraj</label><input value={state.region} onChange={(e)=>set("region",e.target.value)} required={state.status!=="DRAFT"}/></div><div className={styles.field}><label>Okres</label><input value={state.district} onChange={(e)=>set("district",e.target.value)}/></div><div className={styles.field}><label>Obec / mesto</label><input value={state.city} onChange={(e)=>set("city",e.target.value)} required={state.status!=="DRAFT"}/></div><div className={styles.field}><label>Presnosť verejnej mapy</label><select value={state.publicLocationPrecision} onChange={(e)=>set("publicLocationPrecision",e.target.value as PublicLocationPrecision)}><option value="MUNICIPALITY">Obec</option><option value="NEIGHBORHOOD">Časť mesta</option><option value="APPROXIMATE">Približný bod</option></select></div><div className={styles.field}><label>Približná šírka</label><input inputMode="decimal" value={state.publicLatitude} onChange={(e)=>set("publicLatitude",e.target.value)}/></div><div className={styles.field}><label>Približná dĺžka</label><input inputMode="decimal" value={state.publicLongitude} onChange={(e)=>set("publicLongitude",e.target.value)}/></div></div><div className={styles.field}><label>Verejný opis miesta</label><textarea rows={3} value={state.locationDescription} onChange={(e)=>set("locationDescription",e.target.value)} placeholder="napr. okolie parku pri centre obce"/></div><small className={styles.help}>Nezadávaj domácu adresu. Súradnice musia byť už pred uložením vhodne anonymizované.</small></section>
      <section className={styles.card}><h2>5. Kontakt, zdroj a súkromie</h2><div className={styles.fieldGrid}><div className={styles.field}><label>Kontaktná osoba — iba admin</label><input value={state.contactName} onChange={(e)=>set("contactName",e.target.value)}/></div><div className={styles.field}><label>Telefón — iba admin</label><input value={state.contactPhone} onChange={(e)=>set("contactPhone",e.target.value)}/></div><div className={styles.field}><label>E-mail — iba admin</label><input type="email" value={state.contactEmail} onChange={(e)=>set("contactEmail",e.target.value)}/></div><div className={styles.field}><label>Zdroj</label><input value={state.source} onChange={(e)=>set("source",e.target.value)}/></div></div><div className={styles.field}><label>Verejná kontaktná poznámka</label><textarea rows={3} value={state.publicContactNote} onChange={(e)=>set("publicContactNote",e.target.value)} placeholder="napr. kontakt sprostredkujeme cez Psipediu"/></div><div className={styles.field}><label>URL pôvodného hlásenia</label><input type="url" value={state.sourceUrl} onChange={(e)=>set("sourceUrl",e.target.value)}/></div></section>
      <section className={styles.card}><h2>6. Životnosť a duplicity</h2><div className={styles.fieldGrid}><div className={styles.field}><label>Expirácia</label><input type="datetime-local" value={state.expiresAt} onChange={(e)=>set("expiresAt",e.target.value)}/><small className={styles.help}>Ak ACTIVE nemá dátum, systém nastaví 30 dní.</small></div><div className={styles.field}><label>Duplicita hlásenia ID</label><input inputMode="numeric" value={state.duplicateOfId} onChange={(e)=>set("duplicateOfId",e.target.value)} placeholder="napr. 152"/></div></div><div className={styles.field}><label>Dôvod označenia duplicity</label><textarea rows={2} value={state.duplicateReason} onChange={(e)=>set("duplicateReason",e.target.value)}/></div><div className={styles.field}><label>Interná moderátorská poznámka</label><textarea rows={4} value={state.internalNote} onChange={(e)=>set("internalNote",e.target.value)}/></div><small className={styles.help}>Duplicita sa nemaže — uloží sa väzba na kanonické hlásenie a záznam sa archivuje.</small></section>
    </div><aside className={styles.preview}><span>{dogReportTypeLabel(state.type)}</span>{state.mainImage?<img src={state.mainImage} alt="Náhľad fotografie"/>:<div style={{aspectRatio:"4/3",display:"grid",placeItems:"center",fontSize:"4rem",background:"#eef2ef",borderRadius:14}}>🐕</div>}<h2>{state.dogName||state.breed||"Pes bez mena"}</h2><p><strong>{dogReportStatusLabel[state.status]}</strong></p><dl><div><dt>Dátum</dt><dd>{state.eventDate||"—"}</dd></div><div><dt>Lokalita</dt><dd>{state.city||"—"}</dd></div><div><dt>Pohlavie</dt><dd>{dogSexLabel[state.sex]}</dd></div></dl>{report&&publicHref&&["ACTIVE","RESOLVED","EXPIRED","ARCHIVED"].includes(state.status)&&<Link href={publicHref} target="_blank">Verejný náhľad ↗</Link>}</aside></div>
    <div className={styles.actions}><Link className={styles.secondary} href="/admin/stratene-najdene">← Späť</Link><div>{report&&<button type="button" className={styles.secondary} disabled={saving||uploading} onClick={()=>void save("DRAFT")}>Uložiť ako koncept</button>}<button type="submit" className={styles.primary} disabled={saving||uploading}>{saving?"Ukladám…":"Uložiť"}</button><button type="button" className={styles.primary} disabled={saving||uploading} onClick={()=>void save("ACTIVE")}>{saving?"Ukladám…":"Publikovať ako aktívne"}</button>{report?.status==="ACTIVE"&&<button type="button" className={styles.secondary} disabled={saving} onClick={()=>void save("RESOLVED")}>Označiť vyriešené</button>}</div></div>
  </form>;
}
