"use client";

import Link from "next/link";
import { useState, type ChangeEvent } from "react";
import type { ManagedBreed } from "@/lib/breed-store";
import { adminImageUploadMessage, uploadAdminImage } from "@/lib/admin-image-upload";

function slugify(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,90);}
function lines(value:string){return value.split("\n").map((item)=>item.replace(/^[-•]\s*/,"").trim()).filter(Boolean);}

export function AdminBreedEditor({ breed }: { breed?: ManagedBreed }) {
  const [form,setForm]=useState({name:breed?.name??"",slug:breed?.slug??"",status:breed?.status??"draft",image:breed?.image??"",imageKey:breed?.imageKey??"",fciGroup:breed?.fciGroup??1,fciSection:breed?.fciSection??"",origin:breed?.origin??"",group:breed?.group??"",size:breed?.size??"",weight:breed?.weight??"",lifespan:breed?.lifespan??"",coat:breed?.coat??"",energy:breed?.energy??3,trainability:breed?.trainability??3,family:breed?.family??3,intro:breed?.intro??"",character:breed?.character??"",needs:breed?.needs??"",goodFor:breed?.goodFor.join("\n")??"",consider:breed?.consider.join("\n")??"",accent:breed?.accent??"forest"});
  const [slugEdited,setSlugEdited]=useState(Boolean(breed)); const [saving,setSaving]=useState(false); const [uploading,setUploading]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const change=(key:keyof typeof form,value:string|number)=>setForm((current)=>({...current,[key]:value}));
  function changeName(value:string){change("name",value);if(!slugEdited)change("slug",slugify(value));}
  async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setUploading(true);setError("");try{const result=await uploadAdminImage(file,"breeds");setForm((current)=>({...current,image:result.imageUrl,imageKey:result.imageKey}));setMessage(adminImageUploadMessage(result,"Ulož plemeno, aby sa obrázok priradil."));}catch(e){setError(e instanceof Error?e.message:"Obrázok sa nepodarilo nahrať.");}finally{setUploading(false);event.target.value="";}}
  async function save(status:"draft"|"published"){setSaving(true);setError("");setMessage("");try{const response=await fetch(breed?`/api/admin/breeds/${breed.id}`:"/api/admin/breeds",{method:breed?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,status,goodFor:lines(form.goodFor),consider:lines(form.consider)})});const data=await response.json() as {breed?:ManagedBreed;error?:string};if(!response.ok||!data.breed)throw new Error(data.error||"Plemeno sa nepodarilo uložiť.");setMessage(status==="published"?"Plemeno je publikované v atlase.":"Koncept je uložený.");if(!breed)window.location.assign(`/admin/plemena/${data.breed.id}`);}catch(e){setError(e instanceof Error?e.message:"Plemeno sa nepodarilo uložiť.");}finally{setSaving(false);}}
  return <form className="admin-breed-editor" onSubmit={(event)=>{event.preventDefault();void save("draft");}}>
    <section className="admin-form-card"><div className="admin-field-grid"><label className="admin-field"><span>Názov plemena</span><input required value={form.name} onChange={(e)=>changeName(e.target.value)}/></label><label className="admin-field"><span>URL adresa</span><input required value={form.slug} onChange={(e)=>{setSlugEdited(true);change("slug",e.target.value)}}/></label></div><label className="admin-field"><span>Krátky úvod</span><textarea required value={form.intro} onChange={(e)=>change("intro",e.target.value)}/></label></section>
    <section className="admin-form-card"><h2>Základné údaje</h2><div className="admin-field-grid"><label className="admin-field"><span>FCI skupina</span><input type="number" min="1" max="10" value={form.fciGroup} onChange={(e)=>change("fciGroup",Number(e.target.value))}/></label><label className="admin-field"><span>FCI sekcia</span><input value={form.fciSection} onChange={(e)=>change("fciSection",e.target.value)}/></label><label className="admin-field"><span>Krajina pôvodu</span><input value={form.origin} onChange={(e)=>change("origin",e.target.value)}/></label><label className="admin-field"><span>Skupina / využitie</span><input value={form.group} onChange={(e)=>change("group",e.target.value)}/></label><label className="admin-field"><span>Veľkosť</span><input value={form.size} onChange={(e)=>change("size",e.target.value)}/></label><label className="admin-field"><span>Hmotnosť</span><input value={form.weight} onChange={(e)=>change("weight",e.target.value)}/></label><label className="admin-field"><span>Dĺžka života</span><input value={form.lifespan} onChange={(e)=>change("lifespan",e.target.value)}/></label><label className="admin-field"><span>Srsť</span><input value={form.coat} onChange={(e)=>change("coat",e.target.value)}/></label></div></section>
    <section className="admin-form-card"><h2>Povaha a potreby</h2><label className="admin-field"><span>Charakter</span><textarea value={form.character} onChange={(e)=>change("character",e.target.value)}/></label><label className="admin-field"><span>Každodenné potreby</span><textarea value={form.needs} onChange={(e)=>change("needs",e.target.value)}/></label><div className="admin-field-grid"><label className="admin-field"><span>Vhodné pre — jedna položka na riadok</span><textarea value={form.goodFor} onChange={(e)=>change("goodFor",e.target.value)}/></label><label className="admin-field"><span>Čo zvážiť — jedna položka na riadok</span><textarea value={form.consider} onChange={(e)=>change("consider",e.target.value)}/></label></div></section>
    <section className="admin-form-card"><h2>Profil a fotografia</h2><div className="admin-field-grid">{([['energy','Energia'],['trainability','Cvičiteľnosť'],['family','Vhodnosť do rodiny']] as const).map(([key,label])=><label className="admin-field" key={key}><span>{label} (1–5)</span><input type="number" min="1" max="5" value={form[key]} onChange={(e)=>change(key,Number(e.target.value))}/></label>)}<label className="admin-field"><span>Farebný motív</span><select value={form.accent} onChange={(e)=>change("accent",e.target.value)}><option value="forest">Zelený</option><option value="coral">Koralový</option><option value="gold">Zlatý</option><option value="blue">Modrý</option></select></label></div><label className="admin-field"><span>Fotografia (JPG, PNG, WebP alebo AVIF do 8 MB)</span><input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={(e)=>void upload(e)} disabled={uploading}/><small>{uploading?"Nahrávam…":form.image||"Zatiaľ bez fotografie"}</small></label>{form.image&&<img className="admin-breed-preview" src={form.image} alt="Náhľad plemena"/>}</section>
    {error&&<p className="admin-form-error" role="alert">{error}</p>}{message&&<p className="admin-flash" role="status">{message}</p>}
    <div className="admin-editor-actions"><Link href="/admin/plemena">Späť</Link><div><button type="submit" disabled={saving}>Uložiť koncept</button><button type="button" className="is-primary" disabled={saving} onClick={()=>void save("published")}>Publikovať</button></div></div>
  </form>;
}
