import { env } from "cloudflare:workers";
import { cache } from "react";
import { slugifyArticleTitle } from "@/lib/article-store";
import { adoptionStatuses, adoptionSexes, adoptionSizes, compatibilityValues, activityLevels, vaccinationStatuses, adoptionAgeCategory, type AdoptionDog, type AdoptionStatus } from "@/lib/adoption";

export type AdoptionQuery = { q?: string; region?: string; sex?: string; age?: string; size?: string; children?: string; dogs?: string; cats?: string; status?: string; sort?: string; page?: number; pageSize?: number };
export type AdoptionInput = Partial<Omit<AdoptionDog, "id" | "gallery" | "createdAt" | "updatedAt" | "createdBy" | "updatedBy">> & { gallery?: string[] };
type RuntimeBindings = { DB?: D1Database };
const getDb = () => { const db = (env as unknown as RuntimeBindings).DB; return db && typeof db.prepare === "function" ? db : null; };
const requireDb = () => { const db = getDb(); if (!db) throw new Error("Databáza adopcií nie je pripojená."); return db; };

type Row = Record<string, unknown>;
const oneOf = <T extends readonly string[]>(value: unknown, values: T, fallback: T[number]) => values.includes(String(value) as T[number]) ? String(value) as T[number] : fallback;
const parseGallery = (value: unknown) => { try { const parsed = JSON.parse(String(value ?? "[]")); return Array.isArray(parsed) ? parsed.filter((x): x is string => typeof x === "string") : []; } catch { return []; } };
function rowToDog(r: Row): AdoptionDog { return {
  id: Number(r.id), name: String(r.name), slug: String(r.slug), status: oneOf(r.status, adoptionStatuses, "DRAFT"), sex: oneOf(r.sex, adoptionSexes, "UNKNOWN"),
  birthDate: r.birth_date ? String(r.birth_date) : null, approximateAgeMonths: r.approximate_age_months == null ? null : Number(r.approximate_age_months), size: oneOf(r.size, adoptionSizes, "UNKNOWN"), weightKg: r.weight_kg == null ? null : Number(r.weight_kg),
  breedId: r.breed_id == null ? null : Number(r.breed_id), breedName: String(r.breed_name ?? ""), breedSlug: String(r.breed_slug ?? ""), breedMix: Boolean(r.breed_mix), color: String(r.color ?? ""),
  region: String(r.region), district: String(r.district ?? ""), city: String(r.city), organizationId: r.organization_id == null ? null : Number(r.organization_id), organizationName: String(r.organization_name ?? ""), organizationUrl: r.organization_url ? String(r.organization_url) : null,
  mainImage: r.main_image ? String(r.main_image) : null, gallery: parseGallery(r.gallery_json), shortDescription: String(r.short_description), description: String(r.description), temperament: String(r.temperament ?? ""), activityLevel: oneOf(r.activity_level, activityLevels, "UNKNOWN"),
  suitableForChildren: oneOf(r.suitable_for_children, compatibilityValues, "UNKNOWN"), suitableForDogs: oneOf(r.suitable_for_dogs, compatibilityValues, "UNKNOWN"), suitableForCats: oneOf(r.suitable_for_cats, compatibilityValues, "UNKNOWN"), suitableForOtherAnimals: oneOf(r.suitable_for_other_animals, compatibilityValues, "UNKNOWN"), apartmentSuitable: oneOf(r.apartment_suitable, compatibilityValues, "UNKNOWN"), beginnerSuitable: oneOf(r.beginner_suitable, compatibilityValues, "UNKNOWN"), needsExperiencedOwner: oneOf(r.needs_experienced_owner, compatibilityValues, "UNKNOWN"),
  vaccinationStatus: oneOf(r.vaccination_status, vaccinationStatuses, "UNKNOWN"), chipped: oneOf(r.chipped, compatibilityValues, "UNKNOWN"), neutered: oneOf(r.neutered, compatibilityValues, "UNKNOWN"), healthNotes: String(r.health_notes ?? ""), specialNeeds: String(r.special_needs ?? ""), adoptionRequirements: String(r.adoption_requirements ?? ""), externalSourceUrl: r.external_source_url ? String(r.external_source_url) : null,
  contactName: String(r.contact_name ?? ""), contactEmail: r.contact_email ? String(r.contact_email) : null, contactPhone: String(r.contact_phone ?? ""), publishedAt: r.published_at ? String(r.published_at) : null, lastVerifiedAt: r.last_verified_at ? String(r.last_verified_at) : null, createdAt: String(r.created_at), updatedAt: String(r.updated_at), createdBy: String(r.created_by), updatedBy: String(r.updated_by),
}; }

function normalizeUrl(value?: string | null) { const clean = value?.trim() || null; if (!clean) return null; const u = new URL(clean, "https://psipedia.sk"); if (!['http:','https:'].includes(u.protocol)) throw new Error("Odkaz musí používať http alebo https."); return clean; }
function cleanInput(p: AdoptionInput) {
  const name = p.name?.trim() ?? ""; const slug = slugifyArticleTitle(p.slug?.trim() || name); const status = oneOf(p.status, adoptionStatuses, "DRAFT");
  if (!name) throw new Error("Doplň meno psa."); if (!slug) throw new Error("Doplň platnú adresu profilu."); if (!p.city?.trim() || !p.region?.trim()) throw new Error("Doplň mesto a kraj.");
  if ((p.shortDescription?.trim().length ?? 0) < 20) throw new Error("Krátky popis musí mať aspoň 20 znakov."); if ((p.description?.trim().length ?? 0) < 40) throw new Error("Príbeh psa musí mať aspoň 40 znakov.");
  const gallery = (p.gallery ?? []).map(String).map(x => x.trim()).filter(Boolean).slice(0, 20);
  const age = p.approximateAgeMonths == null ? null : Math.max(0, Math.min(300, Math.trunc(Number(p.approximateAgeMonths))));
  return { ...p, name, slug, status, sex: oneOf(p.sex, adoptionSexes, "UNKNOWN"), size: oneOf(p.size, adoptionSizes, "UNKNOWN"), activityLevel: oneOf(p.activityLevel, activityLevels, "UNKNOWN"), vaccinationStatus: oneOf(p.vaccinationStatus, vaccinationStatuses, "UNKNOWN"), suitableForChildren: oneOf(p.suitableForChildren, compatibilityValues, "UNKNOWN"), suitableForDogs: oneOf(p.suitableForDogs, compatibilityValues, "UNKNOWN"), suitableForCats: oneOf(p.suitableForCats, compatibilityValues, "UNKNOWN"), suitableForOtherAnimals: oneOf(p.suitableForOtherAnimals, compatibilityValues, "UNKNOWN"), apartmentSuitable: oneOf(p.apartmentSuitable, compatibilityValues, "UNKNOWN"), beginnerSuitable: oneOf(p.beginnerSuitable, compatibilityValues, "UNKNOWN"), needsExperiencedOwner: oneOf(p.needsExperiencedOwner, compatibilityValues, "UNKNOWN"), chipped: oneOf(p.chipped, compatibilityValues, "UNKNOWN"), neutered: oneOf(p.neutered, compatibilityValues, "UNKNOWN"), approximateAgeMonths: age, gallery, organizationUrl: normalizeUrl(p.organizationUrl), externalSourceUrl: normalizeUrl(p.externalSourceUrl), shortDescription: p.shortDescription!.trim(), description: p.description!.trim(), city: p.city!.trim(), region: p.region!.trim() };
}

export async function listPublicAdoptions(query: AdoptionQuery = {}) {
  const db = getDb(); const page = Math.max(1, Math.trunc(query.page ?? 1)); const pageSize = Math.max(6, Math.min(48, Math.trunc(query.pageSize ?? 18))); if (!db) return { items: [] as AdoptionDog[], total: 0, page, pageSize, pages: 0 };
  const status = ['ACTIVE','RESERVED','ADOPTED'].includes(query.status ?? '') ? query.status! : 'ACTIVE'; const where = ["status = ?"]; const args: unknown[] = [status];
  const eq = (column: string, value?: string) => { if (value) { where.push(`${column} = ?`); args.push(value); } };
  eq('region', query.region); eq('sex', query.sex); eq('size', query.size); if (query.children === 'YES') eq('suitable_for_children','YES'); if (query.dogs === 'YES') eq('suitable_for_dogs','YES'); if (query.cats === 'YES') eq('suitable_for_cats','YES');
  if (query.q?.trim()) { const q = `%${query.q.trim().toLowerCase()}%`; where.push("(lower(name) LIKE ? OR lower(short_description) LIKE ? OR lower(description) LIKE ? OR lower(city) LIKE ? OR lower(breed_name) LIKE ? OR lower(organization_name) LIKE ?)"); args.push(q,q,q,q,q,q); }
  let ageFilter: ((d: AdoptionDog) => boolean) | null = null; if (['PUPPY','YOUNG','ADULT','SENIOR'].includes(query.age ?? '')) ageFilter = d => adoptionAgeCategory(d) === query.age;
  const order = query.sort === 'oldest' ? 'published_at ASC, id ASC' : query.sort === 'name' ? 'name COLLATE NOCASE ASC, id ASC' : 'last_verified_at DESC, published_at DESC, id DESC';
  const fetchSize = ageFilter ? Math.min(500, pageSize * page * 6) : pageSize; const offset = ageFilter ? 0 : (page - 1) * pageSize;
  const rows = await db.prepare(`SELECT * FROM adoption_dogs WHERE ${where.join(' AND ')} ORDER BY ${order} LIMIT ? OFFSET ?`).bind(...args, fetchSize, offset).all<Row>();
  if (ageFilter) { const filtered = rows.results.map(rowToDog).filter(ageFilter); const slice = filtered.slice((page - 1) * pageSize, page * pageSize); return { items: slice, total: filtered.length, page, pageSize, pages: Math.ceil(filtered.length / pageSize) }; }
  const count = await db.prepare(`SELECT COUNT(*) AS count FROM adoption_dogs WHERE ${where.join(' AND ')}`).bind(...args).first<{count:number}>(); return { items: rows.results.map(rowToDog), total: Number(count?.count ?? 0), page, pageSize, pages: Math.ceil(Number(count?.count ?? 0) / pageSize) };
}

const getPublicUncached = async (slug: string) => { const db = getDb(); if (!db) return null; const row = await db.prepare("SELECT * FROM adoption_dogs WHERE slug = ? AND status IN ('ACTIVE','RESERVED','ADOPTED') LIMIT 1").bind(slug).first<Row>(); return row ? rowToDog(row) : null; };
export const getPublicAdoptionBySlug = cache(getPublicUncached);
export async function getManagedAdoptionById(id: number) { const row = await requireDb().prepare("SELECT * FROM adoption_dogs WHERE id = ? LIMIT 1").bind(id).first<Row>(); return row ? rowToDog(row) : null; }
export async function listManagedAdoptions(query: AdoptionQuery = {}) { const db=requireDb(); const page=Math.max(1,Math.trunc(query.page??1)); const pageSize=Math.max(10,Math.min(100,Math.trunc(query.pageSize??30))); const where:string[]=[]; const args:unknown[]=[]; if(query.status&&adoptionStatuses.includes(query.status as AdoptionStatus)){where.push('status=?');args.push(query.status);} if(query.q?.trim()){const q=`%${query.q.trim().toLowerCase()}%`;where.push('(lower(name) LIKE ? OR lower(city) LIKE ? OR lower(organization_name) LIKE ?)');args.push(q,q,q);} const sql=where.length?`WHERE ${where.join(' AND ')}`:''; const [rows,count]=await Promise.all([db.prepare(`SELECT * FROM adoption_dogs ${sql} ORDER BY updated_at DESC,id DESC LIMIT ? OFFSET ?`).bind(...args,pageSize,(page-1)*pageSize).all<Row>(),db.prepare(`SELECT COUNT(*) AS count FROM adoption_dogs ${sql}`).bind(...args).first<{count:number}>()]); const total=Number(count?.count??0); return {items:rows.results.map(rowToDog),total,page,pageSize,pages:Math.ceil(total/pageSize)}; }

async function resolveBreed(db:D1Database, breedId:number|null|undefined){if(!breedId)return {breedId:null,breedName:'',breedSlug:''};const row=await db.prepare("SELECT id,name,slug FROM managed_breeds WHERE id=? LIMIT 1").bind(breedId).first<{id:number;name:string;slug:string}>();if(!row)throw new Error('Vybrané plemeno neexistuje.');return {breedId:row.id,breedName:row.name,breedSlug:row.slug};}
export async function createManagedAdoption(payload:AdoptionInput, editor:string){const db=requireDb();const p=cleanInput(payload);const breed=await resolveBreed(db,p.breedId);const now=new Date().toISOString();const published=p.status==='ACTIVE'||p.status==='RESERVED'||p.status==='ADOPTED'?now:null;const row=await db.prepare(`INSERT INTO adoption_dogs (name,slug,status,sex,birth_date,approximate_age_months,size,weight_kg,breed_id,breed_name,breed_slug,breed_mix,color,region,district,city,organization_id,organization_name,organization_url,main_image,gallery_json,short_description,description,temperament,activity_level,suitable_for_children,suitable_for_dogs,suitable_for_cats,suitable_for_other_animals,apartment_suitable,beginner_suitable,needs_experienced_owner,vaccination_status,chipped,neutered,health_notes,special_needs,adoption_requirements,external_source_url,contact_name,contact_email,contact_phone,published_at,last_verified_at,created_at,updated_at,created_by,updated_by) VALUES (${Array(48).fill('?').join(',')}) RETURNING *`).bind(p.name,p.slug,p.status,p.sex,p.birthDate??null,p.approximateAgeMonths,p.size,p.weightKg??null,breed.breedId,breed.breedName,breed.breedSlug,p.breedMix?1:0,p.color??'',p.region,p.district??'',p.city,p.organizationId??null,p.organizationName??'',p.organizationUrl??null,p.mainImage??null,JSON.stringify(p.gallery),p.shortDescription,p.description,p.temperament??'',p.activityLevel,p.suitableForChildren,p.suitableForDogs,p.suitableForCats,p.suitableForOtherAnimals,p.apartmentSuitable,p.beginnerSuitable,p.needsExperiencedOwner,p.vaccinationStatus,p.chipped,p.neutered,p.healthNotes??'',p.specialNeeds??'',p.adoptionRequirements??'',p.externalSourceUrl??null,p.contactName??'',p.contactEmail??null,p.contactPhone??'',published,p.lastVerifiedAt??null,now,now,editor,editor).first<Row>();if(!row)throw new Error('Profil sa nepodarilo vytvoriť.');return rowToDog(row);}
export async function updateManagedAdoption(id:number,payload:AdoptionInput,editor:string){const db=requireDb();const old=await getManagedAdoptionById(id);if(!old)return null;const p=cleanInput({...old,...payload});const breed=await resolveBreed(db,p.breedId);const now=new Date().toISOString();const published=(p.status==='ACTIVE'||p.status==='RESERVED'||p.status==='ADOPTED')?(old.publishedAt??now):old.publishedAt;const row=await db.prepare(`UPDATE adoption_dogs SET name=?,slug=?,status=?,sex=?,birth_date=?,approximate_age_months=?,size=?,weight_kg=?,breed_id=?,breed_name=?,breed_slug=?,breed_mix=?,color=?,region=?,district=?,city=?,organization_id=?,organization_name=?,organization_url=?,main_image=?,gallery_json=?,short_description=?,description=?,temperament=?,activity_level=?,suitable_for_children=?,suitable_for_dogs=?,suitable_for_cats=?,suitable_for_other_animals=?,apartment_suitable=?,beginner_suitable=?,needs_experienced_owner=?,vaccination_status=?,chipped=?,neutered=?,health_notes=?,special_needs=?,adoption_requirements=?,external_source_url=?,contact_name=?,contact_email=?,contact_phone=?,published_at=?,last_verified_at=?,updated_at=?,updated_by=? WHERE id=? RETURNING *`).bind(p.name,p.slug,p.status,p.sex,p.birthDate??null,p.approximateAgeMonths,p.size,p.weightKg??null,breed.breedId,breed.breedName,breed.breedSlug,p.breedMix?1:0,p.color??'',p.region,p.district??'',p.city,p.organizationId??null,p.organizationName??'',p.organizationUrl??null,p.mainImage??null,JSON.stringify(p.gallery),p.shortDescription,p.description,p.temperament??'',p.activityLevel,p.suitableForChildren,p.suitableForDogs,p.suitableForCats,p.suitableForOtherAnimals,p.apartmentSuitable,p.beginnerSuitable,p.needsExperiencedOwner,p.vaccinationStatus,p.chipped,p.neutered,p.healthNotes??'',p.specialNeeds??'',p.adoptionRequirements??'',p.externalSourceUrl??null,p.contactName??'',p.contactEmail??null,p.contactPhone??'',published,p.lastVerifiedAt??null,now,editor,id).first<Row>();return row?rowToDog(row):null;}
export const isAdoptionConflict=(e:unknown)=>String(e instanceof Error?e.message:e).includes('UNIQUE constraint failed');
