import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { managedBreeds } from "./schema";

export const adoptionDogs = sqliteTable(
  "adoption_dogs",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    slug: text("slug").notNull(),
    status: text("status").notNull().default("DRAFT"),
    sex: text("sex").notNull().default("UNKNOWN"),
    birthDate: text("birth_date"),
    approximateAgeMonths: integer("approximate_age_months"),
    size: text("size").notNull().default("UNKNOWN"),
    weight: real("weight"),
    breedId: integer("breed_id").references(() => managedBreeds.id, { onDelete: "set null" }),
    breedName: text("breed_name").notNull().default(""),
    breedMix: integer("breed_mix").notNull().default(0),
    color: text("color").notNull().default(""),
    region: text("region").notNull().default(""),
    district: text("district").notNull().default(""),
    city: text("city").notNull().default(""),
    organizationId: integer("organization_id"),
    organizationName: text("organization_name").notNull().default(""),
    organizationSlug: text("organization_slug"),
    mainImage: text("main_image"),
    galleryJson: text("gallery_json").notNull().default("[]"),
    shortDescription: text("short_description").notNull().default(""),
    description: text("description").notNull().default(""),
    temperament: text("temperament").notNull().default(""),
    activityLevel: text("activity_level").notNull().default("UNKNOWN"),
    suitableForChildren: text("suitable_for_children").notNull().default("UNKNOWN"),
    suitableForDogs: text("suitable_for_dogs").notNull().default("UNKNOWN"),
    suitableForCats: text("suitable_for_cats").notNull().default("UNKNOWN"),
    suitableForOtherAnimals: text("suitable_for_other_animals").notNull().default("UNKNOWN"),
    apartmentSuitable: integer("apartment_suitable"),
    beginnerSuitable: integer("beginner_suitable"),
    needsExperiencedOwner: integer("needs_experienced_owner").notNull().default(0),
    vaccinationStatus: text("vaccination_status").notNull().default("UNKNOWN"),
    chipped: integer("chipped"),
    neutered: integer("neutered"),
    healthNotes: text("health_notes").notNull().default(""),
    specialNeeds: text("special_needs").notNull().default(""),
    adoptionRequirements: text("adoption_requirements").notNull().default(""),
    externalSourceUrl: text("external_source_url"),
    contactEmail: text("contact_email"),
    contactPhone: text("contact_phone"),
    contactUrl: text("contact_url"),
    searchText: text("search_text").notNull().default(""),
    publishedAt: text("published_at"),
    lastVerifiedAt: text("last_verified_at"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
    createdBy: text("created_by").notNull(),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("adoption_dogs_slug_unique").on(table.slug),
    index("adoption_dogs_public_status_idx").on(table.status, table.publishedAt, table.updatedAt),
    index("adoption_dogs_region_idx").on(table.status, table.region, table.sex, table.size),
    index("adoption_dogs_verified_idx").on(table.status, table.lastVerifiedAt),
    index("adoption_dogs_org_idx").on(table.organizationId, table.status),
    index("adoption_dogs_breed_idx").on(table.breedId, table.status),
    index("adoption_dogs_admin_updated_idx").on(table.updatedAt, table.id),
  ],
);
