import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const adoptionDogs = sqliteTable(
  "adoption_dogs",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    slug: text("slug").notNull(),
    status: text("status").notNull().default("DRAFT"),
    sex: text("sex").notNull().default("UNKNOWN"),
    birthDate: text("birth_date"),
    approximateAgeMonths: integer("approximate_age_months"),
    size: text("size").notNull().default("UNKNOWN"),
    weightKg: integer("weight_kg"),
    breedId: integer("breed_id"),
    breedName: text("breed_name").notNull().default(""),
    breedSlug: text("breed_slug").notNull().default(""),
    breedMix: integer("breed_mix").notNull().default(0),
    color: text("color").notNull().default(""),
    region: text("region").notNull(),
    district: text("district").notNull().default(""),
    city: text("city").notNull(),
    organizationId: integer("organization_id"),
    organizationName: text("organization_name").notNull().default(""),
    organizationUrl: text("organization_url"),
    mainImage: text("main_image"),
    galleryJson: text("gallery_json").notNull().default("[]"),
    shortDescription: text("short_description").notNull(),
    description: text("description").notNull(),
    temperament: text("temperament").notNull().default(""),
    activityLevel: text("activity_level").notNull().default("UNKNOWN"),
    suitableForChildren: text("suitable_for_children").notNull().default("UNKNOWN"),
    suitableForDogs: text("suitable_for_dogs").notNull().default("UNKNOWN"),
    suitableForCats: text("suitable_for_cats").notNull().default("UNKNOWN"),
    suitableForOtherAnimals: text("suitable_for_other_animals").notNull().default("UNKNOWN"),
    apartmentSuitable: text("apartment_suitable").notNull().default("UNKNOWN"),
    beginnerSuitable: text("beginner_suitable").notNull().default("UNKNOWN"),
    needsExperiencedOwner: text("needs_experienced_owner").notNull().default("UNKNOWN"),
    vaccinationStatus: text("vaccination_status").notNull().default("UNKNOWN"),
    chipped: text("chipped").notNull().default("UNKNOWN"),
    neutered: text("neutered").notNull().default("UNKNOWN"),
    healthNotes: text("health_notes").notNull().default(""),
    specialNeeds: text("special_needs").notNull().default(""),
    adoptionRequirements: text("adoption_requirements").notNull().default(""),
    externalSourceUrl: text("external_source_url"),
    contactName: text("contact_name").notNull().default(""),
    contactEmail: text("contact_email"),
    contactPhone: text("contact_phone").notNull().default(""),
    publishedAt: text("published_at"),
    lastVerifiedAt: text("last_verified_at"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
    createdBy: text("created_by").notNull(),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("adoption_dogs_slug_unique").on(table.slug),
    index("adoption_dogs_public_idx").on(table.status, table.publishedAt, table.updatedAt),
    index("adoption_dogs_location_idx").on(table.status, table.region, table.district, table.city),
    index("adoption_dogs_filters_idx").on(table.status, table.sex, table.size),
    index("adoption_dogs_verification_idx").on(table.status, table.lastVerifiedAt),
    index("adoption_dogs_breed_idx").on(table.breedId, table.status),
    index("adoption_dogs_org_idx").on(table.organizationId, table.status),
  ],
);
