import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { managedBreeds } from "./schema";

export const lostFoundDogReports = sqliteTable(
  "lost_found_dog_reports",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    type: text("type").notNull(),
    status: text("status").notNull().default("DRAFT"),
    slug: text("slug").notNull(),
    dogName: text("dog_name"),
    sex: text("sex").notNull().default("UNKNOWN"),
    breedId: integer("breed_id").references(() => managedBreeds.id, { onDelete: "set null" }),
    breed: text("breed").notNull().default(""),
    breedUnknown: integer("breed_unknown").notNull().default(0),
    color: text("color").notNull().default(""),
    approximateAge: text("approximate_age").notNull().default(""),
    size: text("size").notNull().default("UNKNOWN"),
    description: text("description").notNull().default(""),
    distinguishingMarks: text("distinguishing_marks").notNull().default(""),
    collarDescription: text("collar_description").notNull().default(""),
    chipped: text("chipped").notNull().default("UNKNOWN"),
    mainImage: text("main_image"),
    mainImageKey: text("main_image_key"),
    galleryJson: text("gallery_json").notNull().default("[]"),
    eventDate: text("event_date").notNull().default(""),
    lastSeenDateTime: text("last_seen_date_time"),
    region: text("region").notNull().default(""),
    district: text("district").notNull().default(""),
    city: text("city").notNull().default(""),
    locationDescription: text("location_description").notNull().default(""),
    publicLatitude: real("public_latitude"),
    publicLongitude: real("public_longitude"),
    publicLocationPrecision: text("public_location_precision").notNull().default("MUNICIPALITY"),
    publicContactNote: text("public_contact_note").notNull().default(""),
    source: text("source").notNull().default("EDITORIAL"),
    sourceUrl: text("source_url"),
    searchText: text("search_text").notNull().default(""),
    duplicateOfId: integer("duplicate_of_id"),
    duplicateReason: text("duplicate_reason").notNull().default(""),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
    publishedAt: text("published_at"),
    expiresAt: text("expires_at"),
    resolvedAt: text("resolved_at"),
    archivedAt: text("archived_at"),
  },
  (table) => [
    uniqueIndex("lost_found_dog_reports_type_slug_unique").on(table.type, table.slug),
    index("lost_found_dog_reports_public_idx").on(table.type, table.status, table.eventDate, table.publishedAt),
    index("lost_found_dog_reports_location_idx").on(table.status, table.type, table.region, table.district, table.city),
    index("lost_found_dog_reports_expiry_idx").on(table.status, table.expiresAt),
    index("lost_found_dog_reports_breed_idx").on(table.status, table.type, table.breedId),
    index("lost_found_dog_reports_admin_updated_idx").on(table.updatedAt, table.id),
    index("lost_found_dog_reports_duplicate_idx").on(table.duplicateOfId),
  ],
);

export const lostFoundDogPrivateDetails = sqliteTable(
  "lost_found_dog_private_details",
  {
    reportId: integer("report_id")
      .primaryKey()
      .references(() => lostFoundDogReports.id, { onDelete: "cascade" }),
    contactNameEncrypted: text("contact_name_encrypted"),
    contactPhoneEncrypted: text("contact_phone_encrypted"),
    contactPhoneHash: text("contact_phone_hash"),
    contactEmailEncrypted: text("contact_email_encrypted"),
    contactEmailHash: text("contact_email_hash"),
    privateLocationDescriptionEncrypted: text("private_location_description_encrypted"),
    privateLatitudeEncrypted: text("private_latitude_encrypted"),
    privateLongitudeEncrypted: text("private_longitude_encrypted"),
    verificationNoteEncrypted: text("verification_note_encrypted"),
    privateNoteEncrypted: text("private_note_encrypted"),
    createdBy: text("created_by").notNull(),
    updatedBy: text("updated_by").notNull(),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (table) => [
    index("lost_found_dog_private_phone_hash_idx").on(table.contactPhoneHash),
    index("lost_found_dog_private_email_hash_idx").on(table.contactEmailHash),
  ],
);
