import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const managedArticles = sqliteTable(
  "managed_articles",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    slug: text("slug").notNull(),
    title: text("title").notNull(),
    excerpt: text("excerpt").notNull(),
    category: text("category").notNull(),
    portalSection: text("portal_section").notNull().default("clanky"),
    portalSubpage: text("portal_subpage"),
    status: text("status").notNull().default("draft"),
    accent: text("accent").notNull().default("forest"),
    author: text("author").notNull().default("Redakcia Psipedia"),
    intro: text("intro").notNull(),
    takeaway: text("takeaway").notNull(),
    sectionsJson: text("sections_json").notNull().default("[]"),
    sourcesJson: text("sources_json").notNull().default("[]"),
    blocksJson: text("blocks_json").notNull().default("[]"),
    imageUrl: text("image_url"),
    imageKey: text("image_key"),
    readingMinutes: integer("reading_minutes").notNull().default(5),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
    publishedAt: text("published_at"),
    contentUpdatedAt: text("content_updated_at"),
    showUpdatedLabel: integer("show_updated_label").notNull().default(0),
    seoTitle: text("seo_title").notNull().default(""),
    metaDescription: text("meta_description").notNull().default(""),
    canonicalUrl: text("canonical_url").notNull().default(""),
    noindex: integer("noindex").notNull().default(0),
    focusKeyword: text("focus_keyword").notNull().default(""),
    ogTitle: text("og_title").notNull().default(""),
    ogDescription: text("og_description").notNull().default(""),
    ogImageUrl: text("og_image_url"),
    ogImageKey: text("og_image_key"),
    createdBy: text("created_by").notNull(),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("managed_articles_slug_unique").on(table.slug),
    index("managed_articles_status_published_idx").on(table.status, table.publishedAt),
    index("managed_articles_portal_status_idx").on(table.portalSection, table.status, table.publishedAt),
    index("managed_articles_portal_subpage_idx").on(table.portalSection, table.portalSubpage, table.status, table.publishedAt),
    index("managed_articles_admin_updated_idx").on(table.updatedAt, table.id),
  ],
);

export const managedEvents = sqliteTable(
  "managed_events",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    slug: text("slug").notNull(),
    title: text("title").notNull(),
    excerpt: text("excerpt").notNull(),
    eventType: text("event_type").notNull(),
    status: text("status").notNull().default("draft"),
    startDate: text("start_date").notNull(),
    startTime: text("start_time").notNull().default(""),
    endDate: text("end_date"),
    endTime: text("end_time"),
    venue: text("venue").notNull().default(""),
    city: text("city").notNull(),
    region: text("region").notNull(),
    address: text("address").notNull().default(""),
    organizer: text("organizer").notNull(),
    description: text("description").notNull(),
    practicalInfo: text("practical_info").notNull().default(""),
    websiteUrl: text("website_url"),
    registrationUrl: text("registration_url"),
    imageUrl: text("image_url"),
    imageKey: text("image_key"),
    cancelled: integer("cancelled").notNull().default(0),
    seoJson: text("seo_json").notNull().default("{}"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
    publishedAt: text("published_at"),
    createdBy: text("created_by").notNull(),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("managed_events_slug_unique").on(table.slug),
    index("managed_events_public_date_idx").on(table.status, table.startDate, table.startTime),
    index("managed_events_type_region_idx").on(table.eventType, table.region, table.startDate),
  ],
);

export const directoryProfiles = sqliteTable(
  "directory_profiles",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    category: text("category").notNull(),
    status: text("status").notNull().default("draft"),
    excerpt: text("excerpt").notNull(),
    description: text("description").notNull(),
    servicesJson: text("services_json").notNull().default("[]"),
    qualificationsJson: text("qualifications_json").notNull().default("[]"),
    city: text("city").notNull(),
    district: text("district").notNull().default(""),
    region: text("region").notNull(),
    address: text("address").notNull().default(""),
    online: integer("online").notNull().default(0),
    priceNote: text("price_note").notNull().default(""),
    websiteUrl: text("website_url"),
    internalEmail: text("internal_email"),
    imageUrl: text("image_url"),
    imageKey: text("image_key"),
    importKey: text("import_key"),
    sourceDataJson: text("source_data_json").notNull().default("{}"),
    searchText: text("search_text").notNull().default(""),
    verified: integer("verified").notNull().default(0),
    featured: integer("featured").notNull().default(0),
    seoJson: text("seo_json").notNull().default("{}"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
    publishedAt: text("published_at"),
    createdBy: text("created_by").notNull(),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("directory_profiles_category_slug_unique").on(table.category, table.slug),
    uniqueIndex("directory_profiles_import_key_unique").on(table.importKey),
    index("directory_profiles_public_idx").on(table.status, table.category, table.region, table.district, table.city),
    index("directory_profiles_public_district_idx").on(table.status, table.category, table.district, table.city),
    index("directory_profiles_public_city_idx").on(table.status, table.category, table.city, table.name),
    index("directory_profiles_public_name_idx").on(table.status, table.category, table.name),
    index("directory_profiles_updated_idx").on(table.updatedAt),
    index("directory_profiles_admin_updated_idx").on(table.updatedAt, table.id),
  ],
);

export const directoryInquiries = sqliteTable(
  "directory_inquiries",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    profileId: integer("profile_id"),
    profileName: text("profile_name").notNull(),
    profileSlug: text("profile_slug").notNull(),
    profileCategory: text("profile_category").notNull(),
    recipientEmail: text("recipient_email"),
    senderName: text("sender_name").notNull(),
    senderEmail: text("sender_email").notNull(),
    senderPhone: text("sender_phone").notNull().default(""),
    dogInfo: text("dog_info").notNull().default(""),
    message: text("message").notNull(),
    status: text("status").notNull().default("new"),
    consent: integer("consent").notNull().default(1),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (table) => [
    index("directory_inquiries_status_created_idx").on(table.status, table.createdAt),
    index("directory_inquiries_profile_idx").on(table.profileId, table.createdAt),
    index("directory_inquiries_email_idx").on(table.senderEmail, table.createdAt),
  ],
);

export const directoryProfileChangeRequests = sqliteTable(
  "directory_profile_change_requests",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    profileId: integer("profile_id").notNull(),
    profileName: text("profile_name").notNull(),
    profileSlug: text("profile_slug").notNull(),
    profileCategory: text("profile_category").notNull(),
    requesterName: text("requester_name").notNull(),
    requesterEmail: text("requester_email").notNull(),
    requesterPhone: text("requester_phone").notNull().default(""),
    requesterRole: text("requester_role").notNull().default(""),
    proposedDataJson: text("proposed_data_json").notNull(),
    note: text("note").notNull().default(""),
    authorized: integer("authorized").notNull().default(1),
    consent: integer("consent").notNull().default(1),
    status: text("status").notNull().default("new"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
    reviewedAt: text("reviewed_at"),
    reviewedBy: text("reviewed_by"),
  },
  (table) => [
    index("directory_profile_change_requests_status_created_idx").on(table.status, table.createdAt),
    index("directory_profile_change_requests_profile_created_idx").on(table.profileId, table.createdAt),
    index("directory_profile_change_requests_email_created_idx").on(table.requesterEmail, table.createdAt),
  ],
);

export const newsTips = sqliteTable(
  "news_tips",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    topic: text("topic").notNull(),
    title: text("title").notNull(),
    summary: text("summary").notNull(),
    sourceUrl: text("source_url"),
    location: text("location").notNull().default(""),
    eventDate: text("event_date"),
    contactName: text("contact_name").notNull().default(""),
    contactEmail: text("contact_email"),
    status: text("status").notNull().default("new"),
    internalNote: text("internal_note").notNull().default(""),
    consent: integer("consent").notNull().default(1),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (table) => [
    index("news_tips_status_created_idx").on(table.status, table.createdAt),
    index("news_tips_contact_created_idx").on(table.contactEmail, table.createdAt),
  ],
);

export const articleFeedback = sqliteTable(
  "article_feedback",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    articlePath: text("article_path").notNull(),
    articleTitle: text("article_title").notNull(),
    helpful: integer("helpful").notNull(),
    missingText: text("missing_text").notNull().default(""),
    createdAt: text("created_at").notNull(),
  },
  (table) => [
    index("article_feedback_path_created_idx").on(table.articlePath, table.createdAt),
    index("article_feedback_helpful_created_idx").on(table.helpful, table.createdAt),
  ],
);

export const legalSettings = sqliteTable("legal_settings", {
  id: integer("id").primaryKey(),
  operatorType: text("operator_type").notNull().default("individual"),
  legalName: text("legal_name").notNull().default(""),
  businessName: text("business_name").notNull().default(""),
  address: text("address").notNull().default(""),
  ico: text("ico").notNull().default(""),
  dic: text("dic").notNull().default(""),
  vatId: text("vat_id").notNull().default(""),
  email: text("email").notNull().default(""),
  phone: text("phone").notNull().default(""),
  registryName: text("registry_name").notNull().default(""),
  registryNumber: text("registry_number").notNull().default(""),
  mediaRegistryNumber: text("media_registry_number").notNull().default(""),
  mediaStatus: text("media_status").notNull().default("not_submitted"),
  rpvsStatus: text("rpvs_status").notNull().default("not_registered"),
  correctionEmail: text("correction_email").notNull().default(""),
  privacyEmail: text("privacy_email").notNull().default(""),
  updatedAt: text("updated_at").notNull(),
  updatedBy: text("updated_by").notNull(),
});

export const navigationItems = sqliteTable(
  "navigation_items",
  {
    id: text("id").primaryKey(),
    label: text("label").notNull(),
    href: text("href").notNull(),
    parentId: text("parent_id"),
    position: integer("position").notNull().default(0),
    visible: integer("visible").notNull().default(1),
    updatedAt: text("updated_at").notNull(),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    index("navigation_items_parent_position_idx").on(table.parentId, table.position),
  ],
);

export const portalSectionSettings = sqliteTable("portal_section_settings", {
  slug: text("slug").primaryKey(),
  label: text("label").notNull(),
  eyebrow: text("eyebrow").notNull(),
  description: text("description").notNull(),
  intro: text("intro").notNull(),
  subpagesJson: text("subpages_json").notNull().default("[]"),
  position: integer("position").notNull().default(0),
  visible: integer("visible").notNull().default(1),
  updatedAt: text("updated_at").notNull(),
  updatedBy: text("updated_by").notNull(),
});

export const managedBreeds = sqliteTable(
  "managed_breeds",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    status: text("status").notNull().default("draft"),
    imageUrl: text("image_url").notNull().default(""),
    imageKey: text("image_key"),
    galleryJson: text("gallery_json").notNull().default("[]"),
    fciGroup: integer("fci_group").notNull(),
    fciSection: text("fci_section").notNull(),
    origin: text("origin").notNull(),
    groupName: text("group_name").notNull(),
    size: text("size").notNull(),
    weight: text("weight").notNull(),
    height: text("height").notNull().default(""),
    lifespan: text("lifespan").notNull(),
    coat: text("coat").notNull(),
    energy: integer("energy").notNull().default(3),
    trainability: integer("trainability").notNull().default(3),
    family: integer("family").notNull().default(3),
    children: integer("children").notNull().default(3),
    otherDogs: integer("other_dogs").notNull().default(3),
    apartment: integer("apartment").notNull().default(3),
    grooming: integer("grooming").notNull().default(3),
    shedding: integer("shedding").notNull().default(3),
    preyDrive: integer("prey_drive").notNull().default(3),
    intro: text("intro").notNull(),
    character: text("character").notNull(),
    needs: text("needs").notNull(),
    history: text("history").notNull().default(""),
    exercise: text("exercise").notNull().default(""),
    training: text("training").notNull().default(""),
    health: text("health").notNull().default(""),
    healthRisksJson: text("health_risks_json").notNull().default("[]"),
    goodForJson: text("good_for_json").notNull().default("[]"),
    considerJson: text("consider_json").notNull().default("[]"),
    sourcesJson: text("sources_json").notNull().default("[]"),
    accent: text("accent").notNull().default("forest"),
    seoJson: text("seo_json").notNull().default("{}"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
    publishedAt: text("published_at"),
    createdBy: text("created_by").notNull(),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("managed_breeds_slug_unique").on(table.slug),
    index("managed_breeds_public_idx").on(table.status, table.fciGroup, table.name),
  ],
);

export const helpCases = sqliteTable(
  "help_cases",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    slug: text("slug").notNull(),
    title: text("title").notNull(),
    category: text("category").notNull(),
    status: text("status").notNull().default("draft"),
    excerpt: text("excerpt").notNull(),
    description: text("description").notNull(),
    organization: text("organization").notNull(),
    dogName: text("dog_name").notNull().default(""),
    breed: text("breed").notNull().default(""),
    ageNote: text("age_note").notNull().default(""),
    city: text("city").notNull(),
    region: text("region").notNull(),
    locationNote: text("location_note").notNull().default(""),
    reportedDate: text("reported_date"),
    deadlineDate: text("deadline_date"),
    actionLabel: text("action_label").notNull(),
    actionUrl: text("action_url"),
    contactNote: text("contact_note").notNull().default(""),
    goalAmount: integer("goal_amount"),
    raisedAmount: integer("raised_amount"),
    imageUrl: text("image_url"),
    imageKey: text("image_key"),
    verified: integer("verified").notNull().default(0),
    urgent: integer("urgent").notNull().default(0),
    resolved: integer("resolved").notNull().default(0),
    seoJson: text("seo_json").notNull().default("{}"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
    publishedAt: text("published_at"),
    createdBy: text("created_by").notNull(),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("help_cases_category_slug_unique").on(table.category, table.slug),
    index("help_cases_public_idx").on(table.status, table.category, table.resolved, table.urgent, table.updatedAt),
    index("help_cases_region_idx").on(table.region, table.category, table.status),
  ],
);
