import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const managedArticles = sqliteTable(
  "managed_articles",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    slug: text("slug").notNull(),
    title: text("title").notNull(),
    excerpt: text("excerpt").notNull(),
    category: text("category").notNull(),
    portalSection: text("portal_section").notNull().default("clanky"),
    status: text("status").notNull().default("draft"),
    accent: text("accent").notNull().default("forest"),
    author: text("author").notNull().default("Redakcia Psipedia"),
    intro: text("intro").notNull(),
    takeaway: text("takeaway").notNull(),
    sectionsJson: text("sections_json").notNull().default("[]"),
    sourcesJson: text("sources_json").notNull().default("[]"),
    imageUrl: text("image_url"),
    imageKey: text("image_key"),
    readingMinutes: integer("reading_minutes").notNull().default(5),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
    publishedAt: text("published_at"),
    createdBy: text("created_by").notNull(),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("managed_articles_slug_unique").on(table.slug),
    index("managed_articles_status_published_idx").on(table.status, table.publishedAt),
    index("managed_articles_portal_status_idx").on(table.portalSection, table.status, table.publishedAt),
  ],
);

export const managedEvents = sqliteTable(
  "managed_events",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    slug: text("slug").notNull(),
    title: text("title").notNull(),
    excerpt: text("excerpt").notNull(),
    eventType: text("event_type").notNull(),
    status: text("status").notNull().default("draft"),
    startDate: text("start_date").notNull(),
    startTime: text("start_time").notNull().default(""),
    endDate: text("end_date"),
    endTime: text("end_time"),
    venue: text("venue").notNull().default(""),
    city: text("city").notNull(),
    region: text("region").notNull(),
    address: text("address").notNull().default(""),
    organizer: text("organizer").notNull(),
    description: text("description").notNull(),
    practicalInfo: text("practical_info").notNull().default(""),
    websiteUrl: text("website_url"),
    registrationUrl: text("registration_url"),
    imageUrl: text("image_url"),
    imageKey: text("image_key"),
    cancelled: integer("cancelled").notNull().default(0),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
    publishedAt: text("published_at"),
    createdBy: text("created_by").notNull(),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("managed_events_slug_unique").on(table.slug),
    index("managed_events_public_date_idx").on(table.status, table.startDate, table.startTime),
    index("managed_events_type_region_idx").on(table.eventType, table.region, table.startDate),
  ],
);

export const directoryProfiles = sqliteTable(
  "directory_profiles",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    category: text("category").notNull(),
    status: text("status").notNull().default("draft"),
    excerpt: text("excerpt").notNull(),
    description: text("description").notNull(),
    servicesJson: text("services_json").notNull().default("[]"),
    qualificationsJson: text("qualifications_json").notNull().default("[]"),
    city: text("city").notNull(),
    region: text("region").notNull(),
    address: text("address").notNull().default(""),
    online: integer("online").notNull().default(0),
    priceNote: text("price_note").notNull().default(""),
    websiteUrl: text("website_url"),
    internalEmail: text("internal_email"),
    imageUrl: text("image_url"),
    imageKey: text("image_key"),
    verified: integer("verified").notNull().default(0),
    featured: integer("featured").notNull().default(0),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
    publishedAt: text("published_at"),
    createdBy: text("created_by").notNull(),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("directory_profiles_category_slug_unique").on(table.category, table.slug),
    index("directory_profiles_public_idx").on(table.status, table.category, table.region, table.featured),
    index("directory_profiles_updated_idx").on(table.updatedAt),
  ],
);

export const directoryInquiries = sqliteTable(
  "directory_inquiries",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    profileId: integer("profile_id"),
    profileName: text("profile_name").notNull(),
    profileSlug: text("profile_slug").notNull(),
    profileCategory: text("profile_category").notNull(),
    recipientEmail: text("recipient_email"),
    senderName: text("sender_name").notNull(),
    senderEmail: text("sender_email").notNull(),
    senderPhone: text("sender_phone").notNull().default(""),
    dogInfo: text("dog_info").notNull().default(""),
    message: text("message").notNull(),
    status: text("status").notNull().default("new"),
    consent: integer("consent").notNull().default(1),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (table) => [
    index("directory_inquiries_status_created_idx").on(table.status, table.createdAt),
    index("directory_inquiries_profile_idx").on(table.profileId, table.createdAt),
    index("directory_inquiries_email_idx").on(table.senderEmail, table.createdAt),
  ],
);

export const newsTips = sqliteTable(
  "news_tips",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    topic: text("topic").notNull(),
    title: text("title").notNull(),
    summary: text("summary").notNull(),
    sourceUrl: text("source_url"),
    location: text("location").notNull().default(""),
    eventDate: text("event_date"),
    contactName: text("contact_name").notNull().default(""),
    contactEmail: text("contact_email"),
    status: text("status").notNull().default("new"),
    internalNote: text("internal_note").notNull().default(""),
    consent: integer("consent").notNull().default(1),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (table) => [
    index("news_tips_status_created_idx").on(table.status, table.createdAt),
    index("news_tips_contact_created_idx").on(table.contactEmail, table.createdAt),
  ],
);

export const legalSettings = sqliteTable("legal_settings", {
  id: integer("id").primaryKey(),
  operatorType: text("operator_type").notNull().default("individual"),
  legalName: text("legal_name").notNull().default(""),
  businessName: text("business_name").notNull().default(""),
  address: text("address").notNull().default(""),
  ico: text("ico").notNull().default(""),
  dic: text("dic").notNull().default(""),
  vatId: text("vat_id").notNull().default(""),
  email: text("email").notNull().default(""),
  phone: text("phone").notNull().default(""),
  registryName: text("registry_name").notNull().default(""),
  registryNumber: text("registry_number").notNull().default(""),
  mediaRegistryNumber: text("media_registry_number").notNull().default(""),
  mediaStatus: text("media_status").notNull().default("not_submitted"),
  rpvsStatus: text("rpvs_status").notNull().default("not_registered"),
  correctionEmail: text("correction_email").notNull().default(""),
  privacyEmail: text("privacy_email").notNull().default(""),
  updatedAt: text("updated_at").notNull(),
  updatedBy: text("updated_by").notNull(),
});

export const helpCases = sqliteTable(
  "help_cases",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    slug: text("slug").notNull(),
    title: text("title").notNull(),
    category: text("category").notNull(),
    status: text("status").notNull().default("draft"),
    excerpt: text("excerpt").notNull(),
    description: text("description").notNull(),
    organization: text("organization").notNull(),
    dogName: text("dog_name").notNull().default(""),
    breed: text("breed").notNull().default(""),
    ageNote: text("age_note").notNull().default(""),
    city: text("city").notNull(),
    region: text("region").notNull(),
    locationNote: text("location_note").notNull().default(""),
    reportedDate: text("reported_date"),
    deadlineDate: text("deadline_date"),
    actionLabel: text("action_label").notNull(),
    actionUrl: text("action_url"),
    contactNote: text("contact_note").notNull().default(""),
    goalAmount: integer("goal_amount"),
    raisedAmount: integer("raised_amount"),
    imageUrl: text("image_url"),
    imageKey: text("image_key"),
    verified: integer("verified").notNull().default(0),
    urgent: integer("urgent").notNull().default(0),
    resolved: integer("resolved").notNull().default(0),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
    publishedAt: text("published_at"),
    createdBy: text("created_by").notNull(),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("help_cases_category_slug_unique").on(table.category, table.slug),
    index("help_cases_public_idx").on(table.status, table.category, table.resolved, table.urgent, table.updatedAt),
    index("help_cases_region_idx").on(table.region, table.category, table.status),
  ],
);
